image: php:7.2.24

pipelines:
  branches:
    master:
      - step:
          name: unit test
          caches:
            - composer
            - vendor-directory
          script:
            - apt-get update && apt-get install -y git openssh-server
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs
            - ./vendor/bin/phpunit --testsuite "Unit Test Suite"

definitions:
  caches:
    vendor-directory: vendor
